# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-28 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_print_article'),
        ('member', '0004_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(default='', null=True, verbose_name='description')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Activity', verbose_name='activity')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Article', verbose_name='article')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.Team', verbose_name='team')),
            ],
            options={
                'default_permissions': [],
                'ordering': ['team__name', 'activity__name'],
                'verbose_name': 'prestation',
                'verbose_name_plural': 'prestations'
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='prestations',
            field=models.ManyToManyField(blank=True, to='member.Prestation', verbose_name='prestations'),
        ),
    ]
