# Generated by Django 2.0.6 on 2018-08-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_prestation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'default_permissions': [], 'ordering': ['name'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-begin_date'], 'verbose_name': 'subscription', 'verbose_name_plural': 'subscription'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'default_permissions': [], 'ordering': ['name'], 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
