# Generated by Django 2.2.8 on 2020-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_taxreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='order_key',
            field=models.IntegerField(default=None, null=True, verbose_name='order key'),
        ),
    ]
