# Generated by Django 3.1.7 on 2021-09-24 08:57

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_fiscalyear_deletecascade'),
        ('member', '0010_subscriptiontype_order_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThirdAdherent',
        ),
        migrations.CreateModel(
            name='ContactAdherent',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('contacts.abstractcontact',),
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'default_permissions': [], 'ordering': ['order_key'], 'verbose_name': 'subscription type', 'verbose_name_plural': 'subscription types'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'waiting subscription'), (1, 'building subscription'), (2, 'valid subscription'), (3, 'cancel subscription'), (4, 'disbarred subscription')], db_index=True, default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='taxreceipt',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalyear', verbose_name='fiscal year'),
        ),
    ]
