# Generated by Django 3.2.14 on 2022-08-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_fiscalyear_deletecascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestation',
            options={'default_permissions': [], 'ordering': ['id'], 'verbose_name': 'prestation price', 'verbose_name_plural': 'prestation prices'},
        ),
        migrations.AlterField(
            model_name='prestation',
            name='activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='member.activity', verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='member.team', verbose_name='team'),
        ),
        migrations.CreateModel(
            name='TeamPrestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.activity', verbose_name='activity')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.team', verbose_name='team')),
            ],
            options={
                'verbose_name': 'prestation',
                'verbose_name_plural': 'prestations',
                'ordering': ['team__name', 'activity__name'],
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='prestation',
            name='team_prestation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.teamprestation', verbose_name='team prestation'),
        ),
    ]
