# Generated by Django 3.2.14 on 2022-09-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_team_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docadherent',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='member.document', verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='name',
            field=models.CharField(default='default', max_length=50, verbose_name='name'),
        ),
    ]
