# Generated by Django 3.2.16 on 2022-12-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_docadherent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='state',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'unactive'), (2, 'reserval')], db_index=True, default=0, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='unactive',
            field=models.BooleanField(default=False, null=True, verbose_name='unactive'),
        ),
    ]
