# Generated by Django 3.2.20 on 2024-02-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_subscriptiontype_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxreceipt',
            options={'default_permissions': ['change', 'check'], 'ordering': ['year', 'num', 'third'], 'verbose_name': 'tax receipt', 'verbose_name_plural': 'tax receipts'},
        ),
    ]
