# Generated by Django 3.2.20 on 2024-02-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_taxreceipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxreceipt',
            options={'default_permissions': ['change'], 'ordering': ['year', 'num', 'third'], 'verbose_name': 'tax receipt', 'verbose_name_plural': 'tax receipts'},
        ),
        migrations.AlterField(
            model_name='taxreceipt',
            name='num',
            field=models.IntegerField(default=None, null=True, verbose_name='numeros'),
        ),
    ]
