# Generated by Django 4.2 on 2024-09-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_taxreceipt_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unactive',
            field=models.BooleanField(default=False, verbose_name='unactive'),
        ),
    ]
