# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 15:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('adherent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='member.Adherent', verbose_name='adherent')),
            ],
            options={
                'verbose_name': 'degree',
                'verbose_name_plural': 'degrees',
            },
        ),
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='level')),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='member.Activity', verbose_name='activity')),
            ],
            options={
                'verbose_name': 'degree type',
                'verbose_name_plural': 'degree types',
            },
        ),
        migrations.CreateModel(
            name='SubDegreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='level')),
            ],
            options={
                'verbose_name': 'sub degree type',
                'default_permissions': [],
                'verbose_name_plural': 'sub degree types',
            },
        ),
        migrations.AddField(
            model_name='degree',
            name='degree',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='event.DegreeType', verbose_name='degree'),
        ),
        migrations.AddField(
            model_name='degree',
            name='subdegree',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.SubDegreeType', verbose_name='sub degree'),
        ),
    ]
