# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 22:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reduce',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999999.999)], verbose_name='reduce'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_accounting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.CostAccounting', verbose_name='cost accounting'),
        ),
    ]
